# description: Printing Facts in Ubuntu and Centos
# usage: ansible-playbook -i inventories/hybrid/hosts playbooks/basic/ansible-facts.yml -vv
---
- name: Running playbook on Ubuntu hosts
  hosts: grp_cluster
  gather_facts: True
  tasks:

    # Example that prints the gateway for each host
    - debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    # Example that prints uptimes of each host
    - shell: /usr/bin/uptime
      register: result

    - name: Display uptime for a host
      debug:
        var: result
        verbosity: 2

    # Example that prints users of each host
    - shell: /usr/bin/users
      register: result

    - name: Display users present in a host
      debug:
        var: result.stdout_lines
        verbosity: 2

    # Prints `inventory_hostname` of each host
    - name: Display all inventory_hostname known for a host
      debug:
        var: inventory_hostname
        verbosity: 2

    # Prints `ansible_facts` variables from each host
    - name: Display all variables/facts known for a host
      debug:
        var: ansible_facts
        # skipping: [host_ubuntu_1] => {"skipped_reason": "Verbosity threshold not met."}
        verbosity: 3

    # Print FQDN
    - name: Display all variables/facts known for a host
      debug:
        var: ansible_facts.fqdn
        verbosity: 2
