# description: Refresh packages in Ubuntu and Centos
# usage: ansible-playbook -i inventories/hybrid/hosts playbooks/basic/system-updates.yml --ask-become-pass -vv
---
- hosts: grp_ubuntu
  become: yes
  become_method: sudo
  gather_facts: True
  tasks:
  
    - name: Install system updates for ubuntu systems
      shell:
        "apt update"
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"
      tags: [ubuntu, refresh, update]

    - name: Upgrade apt packages for ubuntu systems
      shell:
        "apt upgrade -y"
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"
      tags: [ubuntu, refresh, upgrade]

    - name: Autoremove apt packages for ubuntu systems
      shell:
        "apt autoremove -y"
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"
      tags: [ubuntu, refresh, autoremove]

- hosts: grp_centos
  become: yes
  become_method: sudo
  gather_facts: True
  tasks:
  
    - name: Install system updates for centos systems
      shell:
        "yum update -y"
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
      tags:
        - centos
        - refresh
        - update

    - name: Upgrade yum packages for centos systems
      shell:
        "yum upgrade -y"
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
      tags:
        - centos
        - refresh
        - upgrade

    - name: Autoremove yum packages for centos systems
      shell:
        "yum autoremove -y"
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
      tags:
        - centos
        - refresh
        - autoremove

