# description: Installs kubeadm
# usage: ansible-playbook -i inventories/ubuntu/hosts playbooks/ubuntu/install-kubeadm.yml --ask-become-pass -vv
---
- hosts: grp_kcluster
  strategy: free
  become: yes
  become_method: sudo
  gather_facts: True
  tasks:

    - name: Disable firewall
      shell: "ufw disable"
      tags: [master, worker]

    - name: Disable swap
      shell: "swapoff -a"
      tags: [master, worker]

    - name: Update fstab
      shell: "sed -i '/swap/d' /etc/fstab"
      tags: [master, worker]

    - name: Update fstab
      shell: 
        cmd: |
          cat >>/etc/sysctl.d/kubernetes.conf<<EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
      tags: [master, worker]

    - name: Run sysctl system
      shell: "sysctl --system"
      tags: [master, worker]
